"use client";
import { useEffect, useState, type ReactElement } from "react";
import Link from "next/link";
import { AppShell } from "../../components/app-shell";
import { ErrorState, LoadingState } from "../../components/async-state";
import { api } from "../../lib/api";
interface Dashboard { readonly institution: { readonly name: string }; readonly user: { readonly firstName: string }; readonly metrics: { readonly questions: number; readonly approvedQuestions: number; readonly draftQuestions: number; readonly blueprints: number; readonly papers: number }; readonly recentPapers: readonly { readonly id: string; readonly title: string; readonly totalMarks: number; readonly createdAt: string }[] }
export default function DashboardPage(): ReactElement {
  const [data, setData] = useState<Dashboard>(); const [error, setError] = useState("");
  useEffect(() => { const institution = new URLSearchParams(window.location.search).get("institution"); if (institution) { localStorage.setItem("edugen_institution_id", institution); window.history.replaceState({}, "", "/dashboard"); } void api<Dashboard>("/institutions/dashboard").then(setData).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : "Unable to load dashboard")); }, []);
  return <AppShell>{error ? <ErrorState message={error} /> : !data ? <LoadingState /> : <><header><div><span className="eyebrow">VIP Maths · {data.institution.name}</span><h1>Hello, {data.user.firstName}</h1><p>Your persisted academic workspace at a glance.</p></div><Link className="button" href="/blueprints/new">Generate a paper</Link></header><div className="metric-grid">{[["Questions", data.metrics.questions], ["Approved", data.metrics.approvedQuestions], ["Drafts", data.metrics.draftQuestions], ["Blueprints", data.metrics.blueprints], ["Papers", data.metrics.papers]].map(([label, value]) => <article className="metric" key={label}><strong>{value}</strong><span>{label}</span></article>)}</div><section className="panel"><div className="panel-title"><h2>Recent papers</h2><Link href="/papers">View all</Link></div>{data.recentPapers.length ? <div className="list">{data.recentPapers.map((paper) => <Link className="list-row" href={`/papers/${paper.id}`} key={paper.id}><span><strong>{paper.title}</strong><small>{new Date(paper.createdAt).toLocaleDateString()}</small></span><b>{paper.totalMarks} marks</b></Link>)}</div> : <p className="muted">No papers generated yet.</p>}</section></>}</AppShell>;
}
