"use client";
import { use, useCallback, useEffect, useState, type ReactElement } from "react";
import { AppShell } from "../../../components/app-shell";
import { ErrorState, LoadingState } from "../../../components/async-state";
import { api } from "../../../lib/api";
type View = "QUESTION_PAPER" | "ANSWER_KEY" | "QUESTIONS_WITH_ANSWERS";
interface SnapshotQuestion { readonly order: number; readonly id: string; readonly questionText?: string; readonly options?: readonly { readonly id: string; readonly text: string }[]; readonly marks: number; readonly correctAnswer?: unknown; readonly solution?: string }
interface SnapshotData { readonly metadata: { readonly title: string; readonly totalMarks: number; readonly durationMinutes: number; readonly instructions: readonly string[]; readonly algorithmVersion: string; readonly warnings: readonly unknown[] }; readonly sections: readonly { readonly id: string; readonly name: string; readonly questions: readonly SnapshotQuestion[] }[] }
interface Paper { readonly title: string; readonly createdAt: string; readonly snapshot: { readonly checksum: string; readonly paperData: SnapshotData } }
export default function PaperPage({ params }: { readonly params: Promise<{ id: string }> }): ReactElement { const { id } = use(params); const [view, setView] = useState<View>("QUESTION_PAPER"); const [paper, setPaper] = useState<Paper>(); const [error, setError] = useState(""); const load = useCallback(() => { setPaper(undefined); setError(""); void api<Paper>(`/papers/${id}?view=${view}`).then(setPaper).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : "Unable to load paper")); }, [id, view]); useEffect(load, [load]); return <AppShell><header className="no-print"><div><h1>{paper?.title ?? "Generated paper"}</h1><p>Immutable snapshot review and print view.</p></div><button onClick={() => window.print()}>Print / Save PDF</button></header><div className="tabs no-print">{(["QUESTION_PAPER", "ANSWER_KEY", "QUESTIONS_WITH_ANSWERS"] as const).map((item) => <button className={view === item ? "active" : "quiet"} key={item} onClick={() => setView(item)}>{item.replaceAll("_", " ")}</button>)}</div>{error ? <ErrorState message={error} /> : !paper ? <LoadingState /> : <article className="paper"><div className="paper-heading"><h2>{paper.snapshot.paperData.metadata.title}</h2><p>Time: {paper.snapshot.paperData.metadata.durationMinutes} minutes <span>Total: {paper.snapshot.paperData.metadata.totalMarks} marks</span></p></div><ol className="instructions">{paper.snapshot.paperData.metadata.instructions.map((instruction) => <li key={instruction}>{instruction}</li>)}</ol>{paper.snapshot.paperData.sections.map((section) => <section key={section.id}><h3>{section.name}</h3>{section.questions.map((question) => <div className="paper-question" key={question.id}><div><b>{question.order}.</b> {question.questionText && <span>{question.questionText}</span>}<em>[{question.marks}]</em></div>{question.options && <ol type="A" className="options">{question.options.map((option) => <li key={option.id}>{option.text}</li>)}</ol>}{question.correctAnswer !== undefined && <div className="answer"><strong>Answer:</strong> {typeof question.correctAnswer === "string" ? question.correctAnswer : JSON.stringify(question.correctAnswer)}{question.solution && <p><strong>Solution:</strong> {question.solution}</p>}</div>}</div>)}</section>)}<footer>Snapshot checksum: {paper.snapshot.checksum} · Algorithm {paper.snapshot.paperData.metadata.algorithmVersion}</footer></article>}</AppShell>; }
