"use client";

import { useEffect, useState, type ReactElement } from "react";
import Link from "next/link";
import { AppShell } from "../../components/app-shell";
import { EmptyState, ErrorState, LoadingState } from "../../components/async-state";
import { PageHeader } from "../../components/layout/PageContainer";
import { Card } from "../../components/ui/Card";
import { api } from "../../lib/api";

interface Paper {
  readonly id: string;
  readonly title: string;
  readonly status: string;
  readonly totalMarks: number;
  readonly durationMinutes: number;
  readonly createdAt: string;
  readonly creator: {
    readonly firstName: string;
    readonly lastName: string;
  };
}

interface Page {
  readonly items: readonly Paper[];
}

export default function PapersPage(): ReactElement {
  const [data, setData] = useState<Page>();
  const [error, setError] = useState("");

  const load = () => {
    setError("");
    void api<Page>("/papers")
      .then(setData)
      .catch((cause: unknown) =>
        setError(cause instanceof Error ? cause.message : "Unable to load papers")
      );
  };

  useEffect(() => {
    load();
  }, []);

  return (
    <AppShell>
      <PageHeader
        title="Generated Papers"
        description="Every examination paper is rendered from an immutable SHA-256 snapshot."
        actions={
          <Link href="/blueprints" className="btn btn-primary">
            Generate paper
          </Link>
        }
      />

      {error ? (
        <ErrorState message={error} onRetry={load} />
      ) : !data ? (
        <LoadingState />
      ) : !data.items.length ? (
        <EmptyState
          title="No papers generated yet"
          message="Select a saved blueprint to generate your first examination paper set."
          action={
            <Link href="/blueprints" className="btn btn-primary">
              View Blueprints
            </Link>
          }
        />
      ) : (
        <Card>
          <div className="data-list">
            {data.items.map((paper) => (
              <Link className="data-list-row" href={`/papers/${paper.id}`} key={paper.id}>
                <div>
                  <strong style={{ display: "block", color: "var(--text-primary)", fontSize: "1rem" }}>
                    {paper.title}
                  </strong>
                  <small style={{ color: "var(--text-muted)" }}>
                    Generated by {paper.creator.firstName} {paper.creator.lastName} on{" "}
                    {new Date(paper.createdAt).toLocaleString()}
                  </small>
                </div>
                <div style={{ textAlign: "right" }}>
                  <b style={{ display: "block", color: "var(--brand-primary)", fontSize: "0.9375rem" }}>
                    {paper.totalMarks} marks
                  </b>
                  <small style={{ color: "var(--text-muted)" }}>{paper.durationMinutes} mins</small>
                </div>
              </Link>
            ))}
          </div>
        </Card>
      )}
    </AppShell>
  );
}
